<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOkxwzjj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOkxwzjj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOkxwzjj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOkxwzjj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOkxwzjj\appProdProjectContainer([
    'container.build_hash' => 'Okxwzjj',
    'container.build_id' => '7f74ab43',
    'container.build_time' => 1602166449,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOkxwzjj');
