<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYjx4bu0\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYjx4bu0/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYjx4bu0.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYjx4bu0\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYjx4bu0\appProdProjectContainer([
    'container.build_hash' => 'Yjx4bu0',
    'container.build_id' => '4d114483',
    'container.build_time' => 1602171304,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYjx4bu0');
