<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKn2zvsy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKn2zvsy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKn2zvsy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKn2zvsy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKn2zvsy\appDevDebugProjectContainer([
    'container.build_hash' => 'Kn2zvsy',
    'container.build_id' => '3747be67',
    'container.build_time' => 1603796551,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKn2zvsy');
