<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUz8mofa\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUz8mofa/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUz8mofa.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUz8mofa\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUz8mofa\appDevDebugProjectContainer([
    'container.build_hash' => 'Uz8mofa',
    'container.build_id' => 'b27ef9f1',
    'container.build_time' => 1603126811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUz8mofa');
